// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://xvzbnsruujzexrfnmevv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh2emJuc3J1dWp6ZXhyZm5tZXZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMyMzExMTEsImV4cCI6MjA3ODgwNzExMX0.QtjQMtC16XoFakL3V52NQGWr9Wrli7bhYJw6lV55gHY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);